package zoned.gradle.generation

import org.gradle.configurationcache.extensions.capitalized
import org.jooq.codegen.DefaultGeneratorStrategy
import org.jooq.codegen.GeneratorStrategy
import org.jooq.meta.ColumnDefinition
import org.jooq.meta.Definition
import org.jooq.meta.TableDefinition

/**
 * Custom jOOQ generation strategy for the Zoned framework.
 *
 * ## Sealed Class Pattern for Entities
 *
 * All tables with primary keys generate sealed classes with two states:
 * - `New`: For entities not yet persisted to the database
 * - `Existing`: For entities loaded from the database
 *
 * ## Primary Key Handling: Internal vs External IDs
 *
 * The key design decision is whether the primary key appears in `New`.
 * We use a **naming convention** to distinguish internal vs external IDs:
 *
 * ### Internal IDs (pk column named "id")
 * - Examples: `account.id`, `person.id`, `tag.id`
 * - ID is managed internally by the system:
 *   - Auto-increment by database (INTEGER PRIMARY KEY AUTOINCREMENT)
 *   - UUID generated by DAO layer (TEXT PRIMARY KEY with app-generated UUID)
 * - Caller should NOT provide the ID when creating a new entity
 * - **PK excluded from `New`, included only in `Existing`**
 *
 * ### External IDs (pk column with any other name)
 * - Examples: `property_record.property_id`, `user_flags.user_id`
 * - ID comes from an external system that we don't control
 *   - e.g., Costa Rican property registry (SIRI) assigns property_id
 *   - e.g., Composite foreign keys referencing parent entities
 * - Caller MUST provide the ID when creating a new entity
 * - **PK included in BOTH `New` and `Existing`**
 *
 * This convention uses naming as the signal:
 * - "id" = internally managed, exclude from New
 * - anything else = externally provided, include in New
 *
 * ## Composite Primary Keys
 *
 * Tables with composite primary keys (e.g., junction tables) always have
 * external IDs since they reference other entities. All pk columns are
 * included in both `New` and `Existing`.
 *
 * ## Metadata Fields
 *
 * - `created`: Excluded from both (set by DB DEFAULT CURRENT_TIMESTAMP)
 * - `modified`: Excluded from `New`, included in `Existing` (useful for display/sorting)
 * - `deleted`: Excluded from both (soft delete managed by DAO)
 */
class EntityGenerationStrategy : DefaultGeneratorStrategy() {

    // Metadata fields to exclude from New entity classes
    private val metadataFieldsNew = setOf(
        "created",
        "modified",
        "deleted"
    )

    // Metadata fields to exclude from Existing entity classes
    // Note: `modified` is intentionally NOT excluded - it's useful for display/sorting
    private val metadataFieldsExisting = setOf(
        "created",
        "deleted"
    )

    // Exceptions for singularization
    private val singularizeExceptions = setOf<String>()

    // Check if a field should be excluded for New entities
    private fun isMetadataFieldForNew(definition: Definition): Boolean {
        if (definition !is ColumnDefinition) return false
        return metadataFieldsNew.contains(definition.name.lowercase())
    }

    // Check if a field should be excluded for Existing entities
    private fun isMetadataFieldForExisting(definition: Definition): Boolean {
        if (definition !is ColumnDefinition) return false
        return metadataFieldsExisting.contains(definition.name.lowercase())
    }

    // Get columns for New state (excludes all metadata)
    private fun getColumnsForNew(table: TableDefinition): List<ColumnDefinition> {
        return table.columns.filter { !isMetadataFieldForNew(it) }
    }

    // Get columns for Existing state (includes modified)
    private fun getColumnsForExisting(table: TableDefinition): List<ColumnDefinition> {
        return table.columns.filter { !isMetadataFieldForExisting(it) }
    }

    // Get all primary key columns for a table (supports composite keys)
    private fun getPrimaryKeyColumns(table: TableDefinition): List<ColumnDefinition> {
        val primaryKey = table.primaryKey ?: return emptyList()
        return primaryKey.keyColumns
    }

    // Get first primary key column (for backwards compatibility with hasPrimaryKeyId)
    private fun getPrimaryKeyColumn(table: TableDefinition): ColumnDefinition? {
        return getPrimaryKeyColumns(table).firstOrNull()
    }

    /**
     * Determines if the primary key is "internal" (managed by system) vs "external" (provided by caller).
     *
     * Internal ID convention: single pk column named "id"
     * - These are auto-increment or DAO-generated UUIDs
     * - Excluded from New state
     *
     * External ID: any other pk configuration
     * - Single column with name other than "id" (e.g., property_id from external registry)
     * - Composite keys (e.g., junction tables with foreign key references)
     * - Included in New state because caller must provide them
     */
    private fun isInternalPrimaryKey(table: TableDefinition): Boolean {
        val pkColumns = getPrimaryKeyColumns(table)
        // Internal ID: exactly one pk column named "id"
        return pkColumns.size == 1 && getJavaIdentifierForEntityField(pkColumns.first()) == "id"
    }

    // Standard Java/Kotlin identifier conversion
    // This is used for default jOOQ generated code - tables, records, etc.
    override fun getJavaIdentifier(definition: Definition): String {
        val identifier = super.getJavaIdentifier(definition)
        return identifier.split('_')
            .joinToString("") { it.lowercase().replaceFirstChar { c -> c.uppercase() } }
    }

    // For entity POJO fields, we want camelCase instead of PascalCase
    fun getJavaIdentifierForEntityField(definition: Definition): String {
        val pascalCase = getJavaIdentifier(definition)
        // Convert first letter to lowercase for entity properties
        return pascalCase.first().lowercase() + pascalCase.substring(1)
    }

    // jOOQ names Record/interface members via getJavaMemberName, which (unlike our overridden
    // getJavaIdentifier) does not split on underscores before digits — so a column like `tax_1`
    // would become record member `tax_1` while the custom POJO field is `tax1`, and the generated
    // `Record(value: Pojo)` constructor would reference a non-existent `value.tax_1`. Route column
    // member names through the same camelCase logic so records and POJOs stay in lock-step.
    override fun getJavaMemberName(definition: Definition, mode: GeneratorStrategy.Mode?): String {
        return if (definition is ColumnDefinition) getJavaIdentifierForEntityField(definition)
        else super.getJavaMemberName(definition, mode)
    }

    // From RenamingStrategy - singularize class names
    override fun getJavaClassName(definition: Definition?, mode: GeneratorStrategy.Mode?): String {
        val defaultName = super.getJavaClassName(definition, mode)
        return defaultName.singularize()
    }

    fun String.singularize() = if (singularizeExceptions.contains(this)) { this } else { this.removeSuffix("s") }

    private fun isNullable(column: ColumnDefinition): Boolean {
        return column.type.isNullable
    }

    fun hasPrimaryKeyId(table: TableDefinition): Boolean {
        val pkColumn = getPrimaryKeyColumn(table)
        return pkColumn != null && getJavaIdentifierForEntityField(pkColumn) == "id"
    }

    // From RenamingStrategy - add appropriate interfaces
    override fun getJavaClassImplements(definition: Definition?, mode: GeneratorStrategy.Mode?): MutableList<String> {
        val defs = super.getJavaClassImplements(definition, mode)
        val addl = when (mode) {
            GeneratorStrategy.Mode.RECORD ->  "zoned.framework.db.Record"
            GeneratorStrategy.Mode.POJO ->
//                if (definition is TableDefinition && hasPrimaryKeyId(definition)) {
//                null // Don't add Entity interface here for POJO when using sealed class
//            } else {
                "zoned.framework.db.Entity"
//            }
            GeneratorStrategy.Mode.DEFAULT -> {
                if (definition is TableDefinition) {
                    "zoned.framework.db.EntityTable"
                } else {
                    null
                }
            }
            else -> null
        }
        if (addl != null) {
            return (defs + addl).toMutableList()
        }
        return defs
    }

    /**
     * Generate custom POJO class for entities with the sealed class pattern.
     *
     * All tables with primary keys get sealed classes with New/Existing states.
     * Tables without primary keys get plain data classes (rare edge case).
     */
    fun generateEntitySealedClass(generator: EntityKotlinGenerator, table: TableDefinition, out: org.jooq.codegen.JavaWriter): String {
        val className = getJavaClassName(table, GeneratorStrategy.Mode.POJO)
        val pkColumns = getPrimaryKeyColumns(table)
        val columnsForNew = getColumnsForNew(table)
        val columnsForExisting = getColumnsForExisting(table)

        val sb = StringBuilder()

        // Add header and imports. Field types are emitted fully qualified (see
        // EntityKotlinGenerator.resolveKotlinType), so the only imports needed are the
        // interfaces referenced unqualified in the class declaration below.
        sb.append("package ${generator.getTargetPackage()}.tables.pojos\n\n")
        sb.append("import java.io.Serializable\n")
        sb.append("import zoned.framework.db.Entity\n\n")

        // Use sealed class pattern for any table with a primary key
        val useSealedClass = pkColumns.isNotEmpty()

        // Determine if pk is internal (excluded from New) or external (included in New)
        // See class-level documentation for the naming convention rationale
        val isInternalPk = isInternalPrimaryKey(table)

        // For New state:
        // - Internal pk (named "id"): exclude pk columns
        // - External pk (any other name): include pk columns
        val newStateColumns = if (isInternalPk) {
            columnsForNew.filter { it !in pkColumns }
        } else {
            columnsForNew  // Keep all columns including pk for external IDs
        }

        // For Existing state:
        // - Always exclude pk columns from the main list (they're added first, separately)
        val existingStateColumns = columnsForExisting.filter { it !in pkColumns }

        if (useSealedClass) {
            sb.append("/**\n")
            sb.append(" * This class is generated by jOOQ via Zoned Framework.\n")
            if (isInternalPk) {
                sb.append(" *\n")
                sb.append(" * Internal ID: `id` is managed by the system (auto-increment or DAO-generated UUID).\n")
                sb.append(" * Use New() without id, Existing() includes id.\n")
            } else {
                sb.append(" *\n")
                sb.append(" * External ID: Primary key is provided by caller (external system or foreign key reference).\n")
                sb.append(" * Both New() and Existing() include the primary key fields.\n")
            }
            sb.append(" */\n")
            sb.append("@Suppress(\"UNCHECKED_CAST\")\n")
            sb.append("sealed class $className : Entity, Serializable {\n")

            // New state class
            sb.append("    data class New(\n")
            newStateColumns.forEachIndexed { index, column ->
                val fieldName = getJavaIdentifierForEntityField(column)
                val fieldType = generator.resolveKotlinType(column.type, out)
                val fieldTypeWithNullability = if (isNullable(column)) "$fieldType?" else fieldType
                sb.append("        val $fieldName: $fieldTypeWithNullability")
                if (index < newStateColumns.size - 1) sb.append(",")
                sb.append("\n")
            }
            sb.append("    ) : $className()\n\n")

            // Existing state class (includes pk columns first, then other columns including modified)
            sb.append("    data class Existing(\n")

            // Add pk columns first
            pkColumns.forEachIndexed { index, pkColumn ->
                val pkFieldName = getJavaIdentifierForEntityField(pkColumn)
                val pkFieldType = generator.resolveKotlinType(pkColumn.type, out)
                val pkFieldTypeWithNullability = if (isNullable(pkColumn)) "$pkFieldType?" else pkFieldType
                sb.append("        val $pkFieldName: $pkFieldTypeWithNullability")
                if (index < pkColumns.size - 1 || existingStateColumns.isNotEmpty()) sb.append(",")
                sb.append("\n")
            }

            // Add remaining columns
            existingStateColumns.forEachIndexed { index, column ->
                val fieldName = getJavaIdentifierForEntityField(column)
                val fieldType = generator.resolveKotlinType(column.type, out)
                val fieldTypeWithNullability = if (isNullable(column)) "$fieldType?" else fieldType
                sb.append("        val $fieldName: $fieldTypeWithNullability")
                if (index < existingStateColumns.size - 1) sb.append(",")
                sb.append("\n")
            }
            sb.append("    ) : $className()\n")

            sb.append("}\n")
        } else {
            // Tables without primary keys: generate plain data class (rare edge case)
            sb.append("/**\n * This class is generated by jOOQ via Zoned Framework.\n")
            sb.append(" *\n * Note: This table has no primary key.\n */\n")
            sb.append("@Suppress(\"UNCHECKED_CAST\")\n")
            sb.append("data class $className(\n")

            columnsForNew.forEachIndexed { index, column ->
                val fieldName = getJavaIdentifierForEntityField(column)
                val fieldType = generator.resolveKotlinType(column.type, out)
                val fieldTypeWithNullability = if (isNullable(column)) "$fieldType?" else fieldType
                sb.append("        val $fieldName: $fieldTypeWithNullability")
                if (index < columnsForNew.size - 1) sb.append(",")
                sb.append("\n")
            }

            sb.append("): Entity, Serializable {\n")
            sb.append("}\n")
        }

        return sb.toString()
    }
}