package zoned.gradle.bundle

import org.gradle.api.DefaultTask
import org.gradle.work.DisableCachingByDefault
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Generates BundleConfig.kt with the project's bundle name
 * This allows the framework to know the bundle filename at compile time
 */
@DisableCachingByDefault(because = "Generates bundle config from project state; not worth caching")
open class BundleConfigGenerator : DefaultTask() {

    @TaskAction
    fun generate() {
        val projectName = project.name
        val bundleName = "$projectName.bundle.js"

        // Generate the BundleConfig.kt file in jvmMain/kotlin
        val outputDir = File(project.buildDir, "generated/kotlin/zoned/framework/ui/libs")
        outputDir.mkdirs()

        val outputFile = File(outputDir, "BundleConfig.kt")
        outputFile.writeText("""
            |package zoned.framework.ui.libs
            |
            |/**
            | * Auto-generated bundle configuration
            | * Generated by zoned gradle plugin from project name: $projectName
            | */
            |object BundleConfig {
            |    const val BUNDLE_NAME = "$bundleName"
            |    const val BUNDLE_PATH = "/static/$bundleName"
            |}
            |
        """.trimMargin())

        logger.lifecycle("Generated BundleConfig.kt with bundle name: $bundleName")
    }
}
