package zoned.gradle

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.file.DuplicatesStrategy
import org.gradle.api.tasks.bundling.Tar
import org.gradle.api.tasks.bundling.Zip
import zoned.gradle.bundle.BundleConfigGenerator
import zoned.gradle.bundle.JsBundleConfigurator
import zoned.gradle.db.DatabaseCleaner
import zoned.gradle.db.DatabaseMigrator
import zoned.gradle.enhancements.EnhancementCodeGenerator
import zoned.gradle.enhancements.EnhancementScaffoldTask
import zoned.gradle.generation.JooqGenerator
import zoned.gradle.style.BuildStyleTask

class ZonedPlugin : Plugin<Project> {

    override fun apply(project: Project) {
        project.tasks.register("db-clean", DatabaseCleaner::class.java)
        project.tasks.register("db-migrate", DatabaseMigrator::class.java)
        project.tasks.register("model-generate", JooqGenerator::class.java)
        project.tasks.register("build-style", BuildStyleTask::class.java)
        project.tasks.register("scaffold-enhancement", EnhancementScaffoldTask::class.java) {
            it.group = "zoned"
            it.description = "Scaffold a new enhancement with expect/actual pattern"
        }

        // Register watch script generator
        val generateWatchScript = project.tasks.register("generate-watch-script") {
            it.doLast {
                // Generate improved watch script with hot reload using tmux
                val scriptContent = """
                    #!/bin/bash
                    ##############################################################################
                    # AUTO-GENERATED FILE - DO NOT EDIT!
                    #
                    # This script is generated by the Zoned Gradle plugin.
                    # Source: zoned/gradle-plugin/src/main/kotlin/zoned/gradle/ZonedPlugin.kt
                    #
                    # To modify this script, edit ZonedPlugin.kt and run:
                    #   ./gradlew generate-watch-script
                    # Or it will regenerate automatically on next build.
                    ##############################################################################

                    PORT=9000
                    SERVER_PID=""
                    SESSION_NAME="zoned-watch-${'$'}${'$'}"

                    # Status bar state
                    BUILD_STATE="starting"
                    LAST_BUILD_TIME="--:--:--"
                    DISPLAY_MTIME="--:--:--"
                    POLL_COUNT=0
                    BUILD_SUCCESS=0
                    BUILD_FAIL=0

                    # Check if tmux is available
                    if ! command -v tmux &> /dev/null; then
                        echo "✗ Error: 'tmux' is not installed."
                        echo "  Install: brew install tmux (macOS) or apt install tmux (Linux)"
                        exit 1
                    fi

                    # If not already in tmux, create a new session and re-exec
                    if [ -z "${'$'}TMUX" ]; then
                        exec tmux new-session -s "${'$'}SESSION_NAME" "${'$'}0" "${'$'}@"
                    fi

                    # Get git stats for display
                    get_git_stats() {
                        local zoned_branch mapapp_branch diff_stats commits_ahead last_commit_ago

                        # Get branch names
                        mapapp_branch=${'$'}(git -C . rev-parse --abbrev-ref HEAD 2>/dev/null || echo "?")
                        # Find zoned repo - check common locations
                        local zoned_dir=""
                        for dir in "/expanse/code/startup/zoned" "${'$'}HOME/code/zoned" "../../zoned" "../zoned"; do
                            if [ -d "${'$'}dir/.git" ]; then
                                zoned_dir="${'$'}dir"
                                break
                            fi
                        done
                        zoned_branch=${'$'}([ -n "${'$'}zoned_dir" ] && git -C "${'$'}zoned_dir" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "?")

                        # Get diff stats vs origin/main (or origin/master)
                        local base_branch="origin/main"
                        git -C . rev-parse --verify origin/main &>/dev/null || base_branch="origin/master"

                        # Get insertions/deletions from tracked file changes
                        local tracked_stats=${'$'}(git -C . diff --shortstat ${'$'}base_branch 2>/dev/null)
                        local tracked_ins=${'$'}(echo "${'$'}tracked_stats" | grep -oP '\d+(?= insertion)' || echo "0")
                        local tracked_del=${'$'}(echo "${'$'}tracked_stats" | grep -oP '\d+(?= deletion)' || echo "0")
                        [ -z "${'$'}tracked_ins" ] && tracked_ins=0
                        [ -z "${'$'}tracked_del" ] && tracked_del=0

                        # Count lines in untracked files (new files not yet added to git)
                        local untracked_lines=${'$'}(git -C . ls-files --others --exclude-standard | xargs -r wc -l 2>/dev/null | tail -1 | awk '{print ${'$'}1}')
                        [ -z "${'$'}untracked_lines" ] && untracked_lines=0

                        # Combine tracked + untracked
                        local total_ins=${'$'}((tracked_ins + untracked_lines))
                        local total_del=${'$'}tracked_del
                        diff_stats="+${'$'}total_ins -${'$'}total_del"

                        # Commits ahead of base
                        commits_ahead=${'$'}(git -C . rev-list --count ${'$'}base_branch..HEAD 2>/dev/null || echo "0")

                        # Time since last commit
                        local last_commit_ts=${'$'}(git -C . log -1 --format=%ct 2>/dev/null)
                        if [ -n "${'$'}last_commit_ts" ]; then
                            local now=${'$'}(date +%s)
                            local diff=${'$'}((now - last_commit_ts))
                            local hours=${'$'}((diff / 3600))
                            local mins=${'$'}(((diff % 3600) / 60))
                            last_commit_ago="${'$'}{hours}h${'$'}{mins}m ago"
                        else
                            last_commit_ago="?"
                        fi

                        # Format diff stats with colors (green for +, red for -)
                        local colored_diff=${'$'}(echo "${'$'}diff_stats" | sed 's/+\([0-9]*\)/#[fg=#22c55e]+\1#[default]/g; s/-\([0-9]*\)/#[fg=#ef4444]-\1#[default]/g')
                        echo "zoned:${'$'}zoned_branch // mapapp:${'$'}mapapp_branch | ${'$'}colored_diff | ${'$'}commits_ahead commits | ${'$'}last_commit_ago"
                    }

                    # Configure tmux status bar
                    setup_tmux_status() {
                        tmux set-option -q status on
                        tmux set-option -q status-position bottom
                        tmux set-option -q status-style "bg=#1f2937,fg=#9ca3af"
                        tmux set-option -q status-left-length 120
                        tmux set-option -q status-right-length 30
                        tmux set-option -q status-left ""
                        tmux set-option -q status-right " #[fg=#6b7280]C-e: copy err#[default] "
                        # Hide the window list
                        tmux set-option -q window-status-format ""
                        tmux set-option -q window-status-current-format ""
                        # Enable mouse mode for scroll support
                        tmux set-option -q mouse on

                        # Top bar for git stats using pane border
                        tmux set-option -q pane-border-status top
                        tmux set-option -q pane-border-style "fg=#374151"
                        tmux set-option -q pane-active-border-style "fg=#374151"
                        tmux set-option -q pane-border-format " #[fg=#9ca3af]#{pane_title}#[default] "

                        # Key binding: Ctrl+E to copy last exception to clipboard
                        # Captures without color codes (-e removed), finds last ERROR line
                        # Uses wl-copy (Wayland) or xclip (X11) or xsel as fallback
                        tmux bind-key -n C-e run-shell 'tmux capture-pane -pS -3000 > /tmp/zoned-pane.txt 2>/dev/null; LINE=${'$'}(grep -n "ERROR " /tmp/zoned-pane.txt 2>/dev/null | tail -1 | cut -d: -f1); if [ -z "${'$'}LINE" ]; then LINE=${'$'}(grep -n "FAILURE:\|BUILD FAILED" /tmp/zoned-pane.txt 2>/dev/null | tail -1 | cut -d: -f1); fi; if [ -n "${'$'}LINE" ]; then tail -n +${'$'}LINE /tmp/zoned-pane.txt 2>/dev/null | head -80 | { wl-copy 2>/dev/null || xclip -selection clipboard 2>/dev/null || xsel --clipboard --input 2>/dev/null; }; tmux display-message "Exception copied to clipboard"; else tmux display-message "No exception found"; fi'
                    }

                    # Update git stats in top bar
                    update_git_stats() {
                        local stats=${'$'}(get_git_stats)
                        tmux set-option -q pane-border-format " ${'$'}stats "
                    }

                    # Convert mtime (Unix timestamp) to readable time
                    mtime_to_display() {
                        local mtime="${'$'}1"
                        if [ -n "${'$'}mtime" ]; then
                            # Truncate to integer seconds for date command
                            local secs="${'$'}{mtime%%.*}"
                            date -d "@${'$'}secs" "+%H:%M:%S" 2>/dev/null || echo "--:--:--"
                        else
                            echo "--:--:--"
                        fi
                    }

                    # Update tmux status bar
                    update_status_bar() {
                        local state_display
                        case "${'$'}BUILD_STATE" in
                            watching)  state_display="#[fg=#22c55e]● watching#[default]" ;;
                            building)  state_display="#[fg=#eab308]◐ building#[default]" ;;
                            starting)  state_display="#[fg=#3b82f6]◐ starting#[default]" ;;
                            failed)    state_display="#[fg=#ef4444]✗ failed#[default]" ;;
                            *)         state_display="${'$'}BUILD_STATE" ;;
                        esac

                        local status=" ${'$'}state_display #[fg=#6b7280]│#[default] #[fg=#22c55e]${'$'}BUILD_SUCCESS#[fg=#6b7280]/#[fg=#ef4444]${'$'}BUILD_FAIL#[default] #[fg=#6b7280]│#[default] ${'$'}LAST_BUILD_TIME #[fg=#6b7280]│#[default] ${'$'}DISPLAY_MTIME #[fg=#6b7280]│#[default] #${'$'}POLL_COUNT #[fg=#6b7280]│#[default] :${'$'}PORT "
                        tmux set-option -q status-left "${'$'}status"
                    }

                    # Colorize log output (timestamps and log levels)
                    colorize_output() {
                        local dim=${'$'}'\033[2m'
                        local cyan=${'$'}'\033[36m'
                        local green=${'$'}'\033[32m'
                        local yellow=${'$'}'\033[33m'
                        local red=${'$'}'\033[31m'
                        local reset=${'$'}'\033[0m'

                        sed -u \
                            -e "s/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/${'$'}{dim}&${'$'}{reset}/g" \
                            -e "s/[0-9]\{2\}:[0-9]\{2\}:[0-9]\{2\}/${'$'}{cyan}&${'$'}{reset}/g" \
                            -e "s/\bINFO\b/${'$'}{green}INFO${'$'}{reset}/g" \
                            -e "s/\bWARN\b/${'$'}{yellow}WARN${'$'}{reset}/g" \
                            -e "s/\bWARNING\b/${'$'}{yellow}WARNING${'$'}{reset}/g" \
                            -e "s/\bERROR\b/${'$'}{red}ERROR${'$'}{reset}/g"
                    }

                    echo "🚀 Zoned Hot Reload"
                    echo "   Watching: src/{jvmMain,commonMain,jsMain}/**/*.kt, ~/.m2/repository/io/4rc/zoned*/**/*.jar"
                    echo "   Port: ${'$'}PORT"
                    echo "   Press Ctrl+C to stop"
                    echo ""

                    # Kill any stale processes on port at startup
                    stale_pids=${'$'}(lsof -i:${'$'}PORT -sTCP:LISTEN -t 2>/dev/null)
                    if [ -n "${'$'}stale_pids" ]; then
                        echo "🧹 Cleaning up stale processes on port ${'$'}PORT..."
                        echo "${'$'}stale_pids" | xargs -r kill -9 2>/dev/null || true
                        sleep 0.3
                    fi

                    # Setup tmux status bar and git stats
                    setup_tmux_status
                    update_status_bar
                    update_git_stats

                    # Cleanup on exit
                    cleanup() {
                        trap - SIGINT SIGTERM  # Remove traps to prevent re-entry
                        echo ""
                        echo "Shutting down..."
                        # Kill server
                        if [ -n "${'$'}SERVER_PID" ]; then
                            pkill -TERM -P ${'$'}SERVER_PID 2>/dev/null || true
                            kill ${'$'}SERVER_PID 2>/dev/null || true
                        fi
                        # Kill any remaining processes on port
                        lsof -i:${'$'}PORT -sTCP:LISTEN -t 2>/dev/null | xargs -r kill -9 2>/dev/null || true
                        exit 0
                    }
                    trap cleanup SIGINT SIGTERM

                    kill_server() {
                        # Kill waiter process
                        if [ -n "${'$'}WAITER_PID" ]; then
                            kill ${'$'}WAITER_PID 2>/dev/null || true
                            WAITER_PID=""
                        fi

                        # Kill the gradle process tree if we have the PID
                        if [ -n "${'$'}SERVER_PID" ]; then
                            # Kill entire process group
                            pkill -TERM -P ${'$'}SERVER_PID 2>/dev/null || true
                            kill ${'$'}SERVER_PID 2>/dev/null || true
                            wait ${'$'}SERVER_PID 2>/dev/null || true
                            SERVER_PID=""
                        fi

                        # Kill any process holding the port
                        local pids=${'$'}(lsof -i:${'$'}PORT -sTCP:LISTEN -t 2>/dev/null)
                        if [ -n "${'$'}pids" ]; then
                            echo "${'$'}pids" | xargs -r kill -9 2>/dev/null || true
                        fi

                        # Wait for port to be free (up to 3 seconds)
                        local attempts=0
                        while [ ${'$'}attempts -lt 30 ]; do
                            if ! lsof -i:${'$'}PORT -sTCP:LISTEN -t &>/dev/null; then
                                return 0
                            fi
                            sleep 0.1
                            attempts=${'$'}((attempts + 1))
                        done

                        # Force kill if still occupied
                        pids=${'$'}(lsof -i:${'$'}PORT -sTCP:LISTEN -t 2>/dev/null)
                        if [ -n "${'$'}pids" ]; then
                            echo "⚠️  Force killing stubborn processes on port ${'$'}PORT..."
                            echo "${'$'}pids" | xargs -r kill -9 2>/dev/null || true
                            sleep 0.5
                        fi
                    }

                    timestamp() {
                        date "+%H:%M:%S"
                    }

                    WAITER_PID=""

                    start_server() {
                        # Kill any stale waiter processes
                        if [ -n "${'$'}WAITER_PID" ]; then
                            kill ${'$'}WAITER_PID 2>/dev/null || true
                            WAITER_PID=""
                        fi

                        # Final verification that port is free
                        if lsof -i:${'$'}PORT -sTCP:LISTEN -t &>/dev/null; then
                            echo "⚠️  Port ${'$'}PORT still in use, waiting..."
                            sleep 1
                            lsof -i:${'$'}PORT -sTCP:LISTEN -t 2>/dev/null | xargs -r kill -9 2>/dev/null || true
                            sleep 0.5
                        fi

                        local start_ms=${'$'}(date +%s%3N)
                        echo "🚀 [${'$'}(timestamp)] Starting server..."
                        # Use setsid to run server in a new session, completely detached
                        setsid ./gradlew --console=plain run > >(colorize_output) 2>&1 &
                        SERVER_PID=${'$'}!

                        # Wait for server to be ready (port listening) - track PID to kill later
                        (
                            while ! lsof -i:${'$'}PORT -sTCP:LISTEN -t &>/dev/null; do
                                sleep 0.1
                            done
                            local ready_ms=${'$'}(date +%s%3N)
                            local elapsed=${'$'}((ready_ms - start_ms))
                            echo "✓ [${'$'}(timestamp)] Server ready on port ${'$'}PORT (${'$'}{elapsed}ms)"
                        ) &
                        WAITER_PID=${'$'}!
                    }

                    # Track newest file modification time (includes zoned library)
                    get_newest_mtime() {
                        {
                            find src/jvmMain src/commonMain src/jsMain -name "*.kt" -printf '%T@\n' 2>/dev/null
                            find ~/.m2/repository/io/4rc/zoned* -name "*.jar" -printf '%T@\n' 2>/dev/null
                        } | sort -rn | head -1
                    }

                    # Check if zoned library changed (returns 0 if changed, 1 if not)
                    zoned_changed() {
                        local zoned_mtime=${'$'}(find ~/.m2/repository/io/4rc/zoned* -name "*.jar" -printf '%T@\n' 2>/dev/null | sort -rn | head -1)
                        local src_mtime=${'$'}(find src/jvmMain src/commonMain src/jsMain -name "*.kt" -printf '%T@\n' 2>/dev/null | sort -rn | head -1)
                        [ -n "${'$'}zoned_mtime" ] && [ "${'$'}zoned_mtime" \> "${'$'}src_mtime" ]
                    }

                    build_and_restart() {
                        local pre_build_mtime=${'$'}(get_newest_mtime)

                        BUILD_STATE="building"
                        LAST_BUILD_TIME=${'$'}(date +%H:%M:%S)
                        update_status_bar

                        # Check if zoned changed - if so, need to refresh dependencies
                        local refresh_flag=""
                        if zoned_changed; then
                            echo "🔨 [${'$'}(timestamp)] Building (zoned changed, refreshing dependencies)..."
                            refresh_flag="--refresh-dependencies"
                        else
                            echo "🔨 [${'$'}(timestamp)] Building..."
                        fi

                        local compile_start=${'$'}(date +%s%3N 2>/dev/null || date +%s)
                        # Compile both JVM and JS (skip slow webpack bundling), include build-style for CSS
                        local build_output
                        build_output=${'$'}(./gradlew --parallel --build-cache ${'$'}refresh_flag compileKotlinJvm compileKotlinJs build-style \
                            -x jsBrowserProductionWebpack -x jsProductionExecutableCompileSync \
                            -x compileProductionExecutableKotlinJs -x jsBrowserDistribution 2>&1)
                        local build_status=${'$'}?

                        if [ ${'$'}build_status -eq 0 ]; then
                            local compile_end=${'$'}(date +%s%3N 2>/dev/null || date +%s)
                            local compile_ms=${'$'}((compile_end - compile_start))
                            echo "✓ [${'$'}(timestamp)] Compiled (${'$'}{compile_ms}ms)"
                            # Clear build errors on success
                            rm -f .build_errors
                            BUILD_SUCCESS=${'$'}((BUILD_SUCCESS + 1))
                            BUILD_STATE="watching"
                            update_status_bar
                            # Only kill server AFTER successful compile
                            kill_server
                            start_server
                            # Check if files changed during build
                            local post_build_mtime=${'$'}(get_newest_mtime)
                            if [ "${'$'}post_build_mtime" != "${'$'}pre_build_mtime" ]; then
                                NEEDS_REBUILD=true
                            else
                                NEEDS_REBUILD=false
                            fi
                            return 0
                        else
                            # Build failed - keep server running!
                            echo "${'$'}build_output"
                            echo "✗ [${'$'}(timestamp)] Build failed - server still running, waiting for changes..."
                            # Write errors to .build_errors for Claude to read
                            echo "${'$'}build_output" > .build_errors
                            BUILD_FAIL=${'$'}((BUILD_FAIL + 1))
                            BUILD_STATE="failed"
                            update_status_bar
                            local post_build_mtime=${'$'}(get_newest_mtime)
                            if [ "${'$'}post_build_mtime" != "${'$'}pre_build_mtime" ]; then
                                NEEDS_REBUILD=true
                            else
                                NEEDS_REBUILD=false
                            fi
                            return 1
                        fi
                    }

                    NEEDS_REBUILD=false

                    # Initial build and start
                    echo "📦 Initial build..."
                    if ! build_and_restart; then
                        echo "⚠️  Initial build failed, fix errors and save to retry"
                    fi

                    # Watch for changes using polling (more reliable than entr)
                    LAST_MTIME=${'$'}(get_newest_mtime)
                    DISPLAY_MTIME=${'$'}(mtime_to_display "${'$'}LAST_MTIME")
                    update_status_bar

                    echo "👀 [${'$'}(timestamp)] Watching for changes..."
                    while true; do
                        sleep 1 || break
                        POLL_COUNT=${'$'}((POLL_COUNT + 1))
                        update_status_bar

                        # Update git stats every 30 seconds
                        if [ ${'$'}((POLL_COUNT % 30)) -eq 0 ]; then
                            update_git_stats
                        fi

                        # Check if rebuild was needed from changes during last build
                        if [ "${'$'}NEEDS_REBUILD" = "true" ]; then
                            echo "📝 [${'$'}(timestamp)] Changes during last build, rebuilding..."
                            build_and_restart || true
                            LAST_MTIME=${'$'}(get_newest_mtime)
                            DISPLAY_MTIME=${'$'}(mtime_to_display "${'$'}LAST_MTIME")
                            update_status_bar
                            continue
                        fi

                        CURRENT_MTIME=${'$'}(get_newest_mtime)

                        # Always update mtime display so user can see polling is working
                        NEW_DISPLAY=${'$'}(mtime_to_display "${'$'}CURRENT_MTIME")
                        if [ "${'$'}NEW_DISPLAY" != "${'$'}DISPLAY_MTIME" ]; then
                            DISPLAY_MTIME=${'$'}NEW_DISPLAY
                            update_status_bar
                        fi

                        if [ "${'$'}CURRENT_MTIME" != "${'$'}LAST_MTIME" ]; then
                            echo "📝 [${'$'}(timestamp)] Change detected, rebuilding..."
                            LAST_MTIME=${'$'}CURRENT_MTIME
                            build_and_restart || true
                            LAST_MTIME=${'$'}(get_newest_mtime)
                            DISPLAY_MTIME=${'$'}(mtime_to_display "${'$'}LAST_MTIME")
                            update_status_bar
                        fi
                    done
                    echo "⚠️ [${'$'}(timestamp)] Polling loop exited unexpectedly"

                    cleanup
                """.trimIndent()

                val scriptFile = project.file("watch.sh")
                scriptFile.writeText(scriptContent)
                scriptFile.setExecutable(true)

                // Add to .gitignore if not already there
                val gitignoreFile = project.file(".gitignore")
                if (gitignoreFile.exists()) {
                    val gitignoreContent = gitignoreFile.readText()
                    if (!gitignoreContent.contains("watch.sh")) {
                        gitignoreFile.appendText("\n# Zoned generated files\nwatch.sh\n")
                        project.logger.lifecycle("Added watch.sh to .gitignore")
                    }
                } else {
                    gitignoreFile.writeText("# Zoned generated files\nwatch.sh\n")
                    project.logger.lifecycle("Created .gitignore")
                }

                project.logger.lifecycle("✓ Generated hot reload script: ./watch.sh")
                project.logger.lifecycle("  Features: Fast incremental builds, graceful restarts, port conflict handling")
                project.logger.lifecycle("  Run with: ./watch.sh")
            }
        }

        // Register bundle config generator task
        val bundleConfigTask = project.tasks.register("generate-bundle-config", BundleConfigGenerator::class.java)

        // Register enhancement code generator task
        val enhancementGenTask = project.tasks.register("generate-enhancements", EnhancementCodeGenerator::class.java)

        // Make sure bundle config and enhancements are generated before Kotlin compilation
        project.afterEvaluate {
            project.tasks.findByName("compileKotlinJvm")?.dependsOn(bundleConfigTask, enhancementGenTask)
            project.tasks.findByName("compileKotlinJs")?.dependsOn(enhancementGenTask)
        }

        // Auto-configure JS bundle output filename
        JsBundleConfigurator.configure(project)

        // Create task to write bundle properties directly to processedResources
        val writeBundlePropsTask = project.tasks.register("writeBundleProperties") {
            it.doLast {
                val bundleName = "${project.name}.bundle.js"
                project.logger.lifecycle("Writing bundle config: $bundleName")

                // Write to processedResources which will end up in the JAR
                val resourcesDir = project.file("${project.buildDir}/processedResources/jvm/main")
                resourcesDir.mkdirs()
                val propsFile = project.file("${project.buildDir}/processedResources/jvm/main/zoned-bundle.properties")
                propsFile.writeText("bundle.name=$bundleName\nbundle.path=/static/$bundleName\n")
            }
        }

        // Make jvmMainClasses depend on writeBundleProperties so it runs before the JAR is created
        project.afterEvaluate {
            project.tasks.findByName("jvmMainClasses")?.dependsOn(writeBundlePropsTask)
        }

        // Add generated source directories to Kotlin sourcesets
        project.afterEvaluate {
            try {
                val kotlin = project.extensions.findByName("kotlin")
                if (kotlin != null) {
                    val sourceSetsMethod = kotlin.javaClass.getMethod("sourceSets")
                    val sourceSets = sourceSetsMethod.invoke(kotlin)
                    val getByNameMethod = sourceSets.javaClass.getMethod("getByName", String::class.java)

                    // Add to jvmMain
                    val jvmMain = getByNameMethod.invoke(sourceSets, "jvmMain")
                    val jvmKotlinMethod = jvmMain.javaClass.getMethod("getKotlin")
                    val jvmKotlinSourceSet = jvmKotlinMethod.invoke(jvmMain)
                    val jvmSrcDirMethod = jvmKotlinSourceSet.javaClass.getMethod("srcDir", Any::class.java)
                    jvmSrcDirMethod.invoke(jvmKotlinSourceSet, "${project.buildDir}/generated/kotlin")

                    // Add to jsMain
                    val jsMain = getByNameMethod.invoke(sourceSets, "jsMain")
                    val jsKotlinMethod = jsMain.javaClass.getMethod("getKotlin")
                    val jsKotlinSourceSet = jsKotlinMethod.invoke(jsMain)
                    val jsSrcDirMethod = jsKotlinSourceSet.javaClass.getMethod("srcDir", Any::class.java)
                    jsSrcDirMethod.invoke(jsKotlinSourceSet, "${project.buildDir}/generated/kotlin-js")
                }
            } catch (e: Exception) {
                project.logger.warn("Could not add generated sources to Kotlin sourceset: ${e.message}")
            }
        }

        project.tasks.named("build").configure {
            it.finalizedBy("generate-watch-script")
        }

        // we get a dupe on the gradle-node-plugin
        project.tasks.withType(Tar::class.java).configureEach { tar ->
            tar.rootSpec.duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        }

        project.tasks.withType(Zip::class.java).configureEach { zip ->
            zip.rootSpec.duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        }
    }
}
