package zoned.gradle.enhancements

import org.gradle.api.DefaultTask
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Gradle task that generates enhancement DSL and registry code
 */
open class EnhancementCodeGenerator : DefaultTask() {

    @TaskAction
    fun generate() {
        val scanner = EnhancementScanner(project.logger)
        val implScanner = ImplScanner(project.logger)

        // Find commonMain directory
        val commonMainDir = project.file("src/commonMain/kotlin")
        if (!commonMainDir.exists()) {
            project.logger.lifecycle("No commonMain directory found, skipping enhancement generation")
            return
        }

        // Scan for enhancements
        val enhancements = scanner.scanForEnhancements(commonMainDir)
        project.logger.lifecycle("Found ${enhancements.size} enhancements: ${enhancements.joinToString { it.name }}")

        if (enhancements.isEmpty()) {
            project.logger.lifecycle("No enhancements found, skipping code generation")
            return
        }

        // Scan for implementations in jsMain
        val jsMainDir = project.file("src/jsMain/kotlin")
        val implementations = implScanner.scanForImplementations(jsMainDir)

        // Validate that all enhancements have implementations
        val missingImpls = enhancements.filter { enh ->
            !implScanner.hasImplementation(implementations, enh.objectName)
        }
        if (missingImpls.isNotEmpty()) {
            val message = buildString {
                appendLine("Missing enhancement implementations in jsMain:")
                missingImpls.forEach { enh ->
                    appendLine("  - ${enh.objectName} requires one of:")
                    appendLine("      fun ${enh.expectActualImplName}(element: EnhancementElement, config: ${enh.configClass}) - recommended")
                    appendLine("      fun ${enh.legacyImplName}(element: Element, config: ${enh.configClass}) - legacy")
                }
            }
            throw org.gradle.api.GradleException(message)
        }

        // Generate JVM DSL
        generateJvmDSL(enhancements)

        // Generate JS Registry
        generateJsRegistry(enhancements, implementations, implScanner)

        project.logger.lifecycle("Enhancement code generation complete")
    }

    /**
     * Generate JVM-side DSL extension functions
     */
    private fun generateJvmDSL(enhancements: List<DiscoveredEnhancement>) {
        // Use project-specific package to avoid conflicts
        val projectPackage = "${project.name.lowercase().replace("-", "")}.enhancements"
        val outputDir = File(project.buildDir, "generated/kotlin/${projectPackage.replace(".", "/")}")
        outputDir.mkdirs()

        // Project-specific DSL file name
        val dslFileName = "${project.name.replaceFirstChar { it.uppercase() }.replace("-", "")}EnhancementDSL"

        // Collect imports
        val imports = enhancements.flatMap { enh ->
            listOf(
                "import ${enh.packageName}.${enh.objectName}",
                "import ${enh.packageName}.${enh.configClass}"
            )
        }.distinct()

        // Generate extension function for each enhancement
        val extensionFunctions = enhancements.joinToString("\n\n") { enh ->
            // Convert hyphenated name to camelCase for valid Kotlin identifier
            val functionName = enh.name.toCamelCase()
            """
            |/**
            | * Type-safe DSL for ${enh.name} enhancement.
            | * Adds data-enhancement attributes for client-side initialization.
            | *
            | * Example:
            | * ```
            | * ul {
            | *     $functionName {
            | *         // Configure here
            | *     }
            | *     li { +"Item" }
            | * }
            | * ```
            | */
            |fun CommonAttributeGroupFacade.$functionName(configure: ${enh.configClass}.() -> Unit = {}) {
            |    val config = ${enh.configClass}().apply(configure)
            |    enhance(${enh.objectName}, config)
            |}
            """.trimMargin()
        }

        val code = """
            |package $projectPackage
            |
            |import kotlinx.html.CommonAttributeGroupFacade
            |import kotlinx.serialization.json.Json
            |import zoned.framework.ui.enhancements.Enhancement
            |import zoned.framework.ui.enhancements.EnhancementConfig
            |${imports.joinToString("\n")}
            |
            |/**
            | * Auto-generated by Zoned Gradle Plugin for ${project.name}
            | * Generated from enhancements found in commonMain
            | *
            | * DO NOT EDIT THIS FILE MANUALLY
            | */
            |
            |/**
            | * Generic enhance function that adds data attributes for client-side discovery
            | */
            |fun <TConfig : EnhancementConfig> CommonAttributeGroupFacade.enhance(
            |    enhancement: Enhancement<TConfig>,
            |    config: TConfig
            |) {
            |    val configJson = Json.encodeToString(enhancement.configSerializer, config)
            |    attributes["data-enhancement"] = enhancement.name
            |    attributes["data-enhancement-config"] = configJson
            |}
            |
            |$extensionFunctions
        """.trimMargin()

        val outputFile = File(outputDir, "$dslFileName.kt")
        outputFile.writeText(code)
        project.logger.lifecycle("Generated JVM DSL: ${outputFile.absolutePath}")
    }

    /**
     * Generate JS-side auto-discovery registry
     */
    private fun generateJsRegistry(
        enhancements: List<DiscoveredEnhancement>,
        implementations: Set<String>,
        implScanner: ImplScanner
    ) {
        // Use project-specific package to avoid conflicts
        val projectPackage = "${project.name.lowercase().replace("-", "")}.enhancements"
        val outputDir = File(project.buildDir, "generated/kotlin-js/${projectPackage.replace(".", "/")}")
        outputDir.mkdirs()

        // Project-specific registry name
        val registryName = "${project.name.replaceFirstChar { it.uppercase() }.replace("-", "")}EnhancementRegistry"

        // Collect imports - include impl function imports based on pattern
        val imports = enhancements.flatMap { enh ->
            val implName = implScanner.getImplementationName(implementations, enh.objectName) ?: enh.legacyImplName
            listOf(
                "import ${enh.packageName}.${enh.objectName}",
                "import ${enh.packageName}.${enh.configClass}",
                "import ${enh.packageName}.$implName"
            )
        }.distinct()

        // Generate registration calls
        val registrations = enhancements.joinToString("\n        ") { enh ->
            """register("${enh.name}", ::_init${enh.objectName})"""
        }

        // Generate handler functions - determine wrapping based on implementation function name
        val handlers = enhancements.joinToString("\n\n    ") { enh ->
            val implName = implScanner.getImplementationName(implementations, enh.objectName) ?: enh.legacyImplName
            val usesEnhancementElement = implName.startsWith("init")

            if (usesEnhancementElement) {
                // New pattern (initFoo): wrap Element in EnhancementElement
                """
                |private fun _init${enh.objectName}(element: Element, configJson: String) {
                |    val config = Json.decodeFromString(${enh.objectName}.configSerializer, configJson)
                |    val wrapped = EnhancementElement.wrapOrThrow(element)
                |    $implName(wrapped, config)
                |}
                """.trimMargin()
            } else {
                // Legacy pattern (makeFoo): pass raw Element
                """
                |private fun _init${enh.objectName}(element: Element, configJson: String) {
                |    val config = Json.decodeFromString(${enh.objectName}.configSerializer, configJson)
                |    $implName(element, config)
                |}
                """.trimMargin()
            }
        }

        // Check if any enhancement uses new pattern (needs EnhancementElement import)
        val needsEnhancementElement = enhancements.any { enh ->
            val implName = implScanner.getImplementationName(implementations, enh.objectName) ?: enh.legacyImplName
            implName.startsWith("init")
        }

        val enhancementElementImport = if (needsEnhancementElement) {
            "import zoned.framework.ui.enhancements.EnhancementElement"
        } else ""

        val code = """
            |package $projectPackage
            |
            |import kotlinx.serialization.json.Json
            |import web.dom.Element
            |import web.dom.document
            |import kotlinx.browser.window
            |${if (enhancementElementImport.isNotEmpty()) enhancementElementImport + "\n" else ""}${imports.joinToString("\n")}
            |
            |/**
            | * Auto-generated enhancement registry for ${project.name}
            | * Generated by Zoned Gradle Plugin
            | *
            | * DO NOT EDIT THIS FILE MANUALLY
            | */
            |object $registryName {
            |
            |    private val handlers = mutableMapOf<String, (Element, String) -> Unit>()
            |
            |    init {
            |        $registrations
            |    }
            |
            |    private fun register(name: String, handler: (Element, String) -> Unit) {
            |        handlers[name] = handler
            |    }
            |
            |    /**
            |     * Initialize all enhancements found in the DOM.
            |     * Call this after page load or after HTMX content swaps.
            |     */
            |    fun initialize(root: Element = document.body as Element) {
            |        val elements = root.querySelectorAll("[data-enhancement]")
            |        for (i in 0 until elements.length) {
            |            val element = elements.item(i) ?: continue
            |
            |            // Skip if already enhanced
            |            if (element.hasAttribute("data-enhanced")) continue
            |
            |            val enhancementName = element.getAttribute("data-enhancement") ?: continue
            |            val configJson = element.getAttribute("data-enhancement-config") ?: "{}"
            |
            |            val handler = handlers[enhancementName]
            |            if (handler != null) {
            |                try {
            |                    handler(element, configJson)
            |                    element.setAttribute("data-enhanced", "true")
            |                } catch (e: Exception) {
            |                    console.error("Failed to initialize enhancement '${'$'}enhancementName':", e)
            |                }
            |            } else {
            |                console.warn("No handler registered for enhancement: ${'$'}enhancementName")
            |            }
            |        }
            |    }
            |
            |    $handlers
            |}
        """.trimMargin()

        val outputFile = File(outputDir, "${registryName}.kt")
        outputFile.writeText(code)
        project.logger.lifecycle("Generated JS Registry: ${outputFile.absolutePath}")
    }
}

/**
 * Convert a hyphenated name to camelCase for valid Kotlin identifiers.
 * Example: "leaflet-map" -> "leafletMap"
 */
private fun String.toCamelCase(): String {
    return this.split("-").mapIndexed { index, part ->
        if (index == 0) part.lowercase()
        else part.replaceFirstChar { it.uppercase() }
    }.joinToString("")
}
